#指定Action的名称
name: SelfPage-测试Action

#指定Action的触发条件。[定时，特定条件等...]
#这里的触发条件为每次push到master分支
on:
  push:
    branches: 
      - master

#指定Action的jobs集合，会按顺序依次执行job
jobs:
  #job须包含runs-on步骤,否则出错
  #\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ job //////////////////////////////////////////
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    steps:
      #step须包含uses或run，否则出错
      #uses可使用第三方action
      #++++++++++++++++++++++++++ step +++++++++++++++++++++++++++
      - name: 第一步，拉取master分支
        uses: actions/checkout@master

      #++++++++++++++++++++++++++ step +++++++++++++++++++++++++++
      #- name: 第二步，uses和run只可用一个，冒号右边有个空格
      #  uses: 
      #  run: 

  #\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ job //////////////////////////////////////////
  job-2:
    name: job-2
    runs-on: ubuntu-latest
    steps:
      - name: 第一步，设置环境变量，并输出
        #env若和使用它的step不为同一step则使用无效
        #这里env和使用使用它的step为同一step，则输出 LiuYan
        env:
          SelfPageAuthor: LiuYan
        run: 
          echo $SelfPageAuthor
